// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPartner struct {
	Name string `json:"name"`
	Cep  string `json:"cep"`
}

type Partner struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Cep  string `json:"cep"`
}
