// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Cep          string    `json:"cep"`
	Street       string    `json:"street"`
	Neighborhood string    `json:"neighborhood"`
	City         string    `json:"city"`
	Uf           string    `json:"uf"`
	Location     *Location `json:"location"`
}

type Location struct {
	Type string  `json:"type"`
	Lat  float64 `json:"lat"`
	Lng  float64 `json:"lng"`
}

type NewPartner struct {
	TradingName string `json:"tradingName"`
	OwnerName   string `json:"ownerName"`
	Document    string `json:"document"`
	Cep         string `json:"cep"`
}

type Partner struct {
	ID          string   `json:"id"`
	TradingName string   `json:"tradingName"`
	OwnerName   string   `json:"ownerName"`
	Document    string   `json:"document"`
	Address     *Address `json:"address"`
}
