// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	Cep          string `json:"cep"`
	Street       string `json:"street"`
	Neighborhood string `json:"neighborhood"`
	City         string `json:"city"`
	Uf           string `json:"uf"`
	Type         string `json:"type"`
	Coordinates  []int  `json:"coordinates"`
}

type NewPartner struct {
	TradingName string `json:"tradingName"`
	OwnerName   string `json:"ownerName"`
	Document    string `json:"document"`
	Cep         string `json:"cep"`
}

type Partner struct {
	ID          string   `json:"id"`
	TradingName string   `json:"tradingName"`
	OwnerName   string   `json:"ownerName"`
	Document    string   `json:"document"`
	Address     *Address `json:"address"`
}
